version: "3.9"

services:

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dev_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_pass}
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s


  backend:
    build: ./backend
    environment:
       DATABASE_URL: ${DATABASE_URL:-postgres://dev_user:dev_pass@db:5432/app_db?sslmode=disable}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
